chore: update to use caching build in workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -8,24 +8,94 @@ on:
   workflow_dispatch:
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04 # uses podman from 24.04 or later
     env:
+      REGISTRY: ghcr.io
       IMAGE: ghcr.io/${{ github.repository_owner }}/webhook
+      IMGCACHE_PATH: image_cache.tar
+      # building using docker format is required to make builds
+      # find cached build layers after a save/load cycle
+      BUILDAH_FORMAT: docker
     steps:
-      - uses: docker/login-action@v2.2.0
+      - id: get-release-ver
+        name: Fetch latest release version
+        run: |
+          curl -H 'X-GitHub-API-Version: 2022-11-28' -sS https://api.github.com/repos/adnanh/webhook/releases/latest \
+            | jq -r .tag_name \
+            | sed s/^v// \
+            | xargs -I{} printf 'version=%s\n' {} \
+            > "$GITHUB_OUTPUT"
+
+      - env:
+          USERNAME: ${{ github.actor }}
+          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+        run: printenv PASSWORD | podman login -v ${{ env.REGISTRY }} -u "$USERNAME" --password-stdin
+
+      - id: restore-cache
+        uses: actions/cache/restore@v4
         with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - uses: actions/checkout@v3
-      - run: DOCKER_BUILDKIT=1 docker build -f Containerfile -t ${{ env.IMAGE }} .
-      - name: docker tag ...
+          # we can't precalculate the hash for a key so
+          # set an invalid key and fall back to the most recent cache
+          key: image-cache-INVALID
+          restore-keys: image-cache-
+          path: ${{ env.IMGCACHE_PATH }}
+
+      - name: Import images from cache
+        # skip step if no cache was restored
+        if: steps.restore-cache.outputs.cache-matched-key != ''
+        continue-on-error: true
+        run: |
+          podman load -i "${IMGCACHE_PATH:?}" \
+            || echo "::warning::Failure while importing images from cache"
+          echo
+          echo "Image Status:"
+          podman image list
+
+      - uses: actions/checkout@v4
+
+      # TODO: switch to --pull=newer once supported https://github.com/containers/podman/issues/22845
+      - run: podman build --pull=always --build-arg 'RELEASE_VER=${{ steps.get-release-ver.outputs.version }}' -t ${{ env.IMAGE }} .
+
+      - name: Add image version tag
         run: |
           set -x
           VERSION=$(
-            docker run --rm -i ${{ env.IMAGE }} -version \
+            podman run --rm -i ${{ env.IMAGE }} -version \
               | cut -d ' ' -f 3
           )
           [ -n "$VERSION" ] || exit
-          docker tag ${{ env.IMAGE }} ${{ env.IMAGE }}:"$VERSION"
-      - run: docker push -a ${{ env.IMAGE }}
+          podman tag ${{ env.IMAGE }} ${{ env.IMAGE }}:"$VERSION"
+
+      - run: podman image inspect --format '{{ range .RepoTags }}{{ . }} {{ end }}'
+          ${{ env.IMAGE }} | xargs -n 1 podman push
+
+      - if: ${{ !cancelled() }} # runs even if previous steps failed
+        run: podman logout ${{ env.REGISTRY }}
+
+      - id: export-cache
+        name: Export images to cache
+        continue-on-error: true
+        run: |
+          echo "Existing Images:"
+          podman image list
+          echo
+          echo "Saving Images:"
+          rm -f "${IMGCACHE_PATH:?}"
+          {
+            # build cache (dangling or intermediate images that have labeled root ancestors)
+            for img in $(podman image list -q --filter dangling=true) $(podman image list -q --filter intermediate=true); do
+              root=$( i="$img" t="$i"; while [ -n "$i" ]; do t="$i" i="$(podman image inspect -f '{{ .Parent }}' "$i")"; done; echo "$t"; )
+              [ "$(podman image inspect -f '{{ len .RepoTags }}' "$root")" -gt 0 ] && echo "$img"
+            done
+            # labeled images
+            podman image list --filter dangling=false --format '{{ range .Names }}{{ . }} {{ end }}' | xargs -n 1 | sort -u
+          } \
+            | tee /dev/stderr \
+            | xargs podman save -m -o "${IMGCACHE_PATH:?}" \
+            || echo "::error::Failure while exporting images to cache"
+
+      - uses: actions/cache/save@v4
+        if: steps.export-cache.outcome == 'success' && !endsWith(steps.restore-cache.outputs.cache-matched-key, hashFiles(env.IMGCACHE_PATH))
+        with:
+          key: image-cache-${{ hashFiles(env.IMGCACHE_PATH) }}
+          path: ${{ env.IMGCACHE_PATH }}
